[project]
name = "mlflow-ngrok-integration"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "mlflow[auth]>=2.21.0",
    "pyngrok>=7.2.3",
    "typing-extensions>=4.12.2",
]
